openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of students app
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Authentication
    description: Authentication operations.
servers:
  - url: http://localhost:8000
  - url: https://contacts-app-vs9l.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/authentication/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/authentication/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/authentication/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/authentication/refresh.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/authentication/send-reset-email.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/authentication/reset-pwd.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
